#!/usr/bin/tclsh

# M144 demo for extra joints 
# Usage: M144 [Pjoint_num] [Qposition]

# Mcodes substitute "-1.000000" for omitted p,q values
# so these are handled as special cases

set min_joint_num  4
set max_joint_num 15
proc fail {msg} {
  puts "\n$::argv0:FAIL $msg"
  puts "Usage: $::argv0 P<jointnumber> Q<position>"
  exit 1
}

set p [lindex $::argv 0]
set q [lindex $::argv 1]
if {"$p" == "-1.000000"} {fail "Missing P value"}
if {"$q" == "-1.000000"} {fail "Missing Q value"}

if {$p < $min_joint_num || $p > $max_joint_num} {fail "Bad P value <$p>"}

set p [expr int($p)]

set cmd "halcmd setp j${p}.limit3.in $q"
puts "\n$::argv0: $cmd"
eval exec $cmd
exit 0
